# -*- coding: utf-8 -*-
"""expense tracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABBIiba-xinjUwg-DPTLujKcMIeRsDgs
"""

expenses = {}


def add_expense():
    item = input("Enter item: ")
    amount = float(input("Enter amount: "))

    expenses[item] = amount

    print("Expense added successfully")

def view_expenses():

    if not expenses:
        print("No expenses found")
        return

    print("\nExpenses:")

    for item, amount in expenses.items():
        print(item, ":", amount)

    print("Total =", total_expense())


def total_expense():
    return sum(expenses.values())


def highest_expense():

    if expenses:
        item = max(expenses, key=expenses.get)

        # Tuple
        result = (item, expenses[item])

        print("Highest Expense:", result)

while True:

    print("\n--- Expense Tracker ---")
    print("1. Add Expense")
    print("2. View Expenses")
    print("3. Highest Expense")
    print("4. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        add_expense()

    elif choice == "2":
        view_expenses()

    elif choice == "3":
        highest_expense()

    elif choice == "4":
        print("Thank You")
        break

    else:
        print("Invalid Choice")