# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IACns0Y_tFgtPBls4Ux0kknacnQS4N_B
"""

FILE_NAME = "tasks.txt"


def load_tasks():
    tasks = []
    try:
        file = open(FILE_NAME, "r")
        for line in file:
            line = line.strip()
            if line:
                parts = line.split(" | ")
                if len(parts) == 3:
                    tasks.append(parts)
        file.close()
    except:
        pass
    return tasks


def save_tasks(tasks):
    file = open(FILE_NAME, "w")
    for task in tasks:
        file.write(task[0] + " | " + task[1] + " | " + task[2] + "\n")
    file.close()


def view_tasks(tasks):
    if len(tasks) == 0:
        print("\nNo tasks found.")
        return
    print("\n--- Your Tasks ---")
    count = 1
    for task in tasks:
        print(str(count) + ". [" + task[2] + "] " + task[0] + " - " + task[1])
        count = count + 1


def add_task(tasks):
    print("\n--- Add New Task ---")
    deadline = input("Enter deadline (DD-MM-YYYY\): ")
    description = input("Enter task description: ")
    tasks.append([deadline, description, "pending"])
    save_tasks(tasks)
    print("Task added successfully!")


def mark_complete(tasks):
    view_tasks(tasks)
    if len(tasks) == 0:
        return
    choice = input("\nEnter task number to mark as completed: ")
    index = int(choice) - 1
    if index >= 0 and index < len(tasks):
        tasks[index][2] = "completed"
        save_tasks(tasks)
        print("Task marked as completed!")
    else:
        print("Invalid task number.")


def main():
    print("=== Task Manager CLI ===")
    tasks = load_tasks()

    while True:
        print("\n--- Menu ---")
        print("1. View Tasks")
        print("2. Add Task")
        print("3. Mark Task as Completed")
        print("4. Exit")

        choice = input("\nEnter your choice: ")

        if choice == "1":
            view_tasks(tasks)
        elif choice == "2":
            add_task(tasks)
        elif choice == "3":
            mark_complete(tasks)
        elif choice == "4":
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Try again.")


main()