# -*- coding: utf-8 -*-
"""tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbLANl8usIN2z4qp9GPafm4nUPGxctiU
"""

# python-progress-tracker
# Phase 1 — Log and view study sessions
# Built by: Hiya

# Simple Progress Tracker (No imports)

while True:
    print("\n--- Progress Tracker ---")
    print("1. Add Study Session")
    print("2. View Progress")
    print("3. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        date = input("Enter date (YYYY-MM-DD): ")
        topic = input("What did you study today? ")
        hours = input("How many hours did you study? ")

        file = open("progress.txt", "a")
        file.write(date + " | " + topic + " | " + hours + "\n")
        file.close()

        print("Progress saved!")

    elif choice == "2":
        try:
            file = open("progress.txt", "r")
            lines = file.readlines()
            file.close()

            total = 0

            print("\nYour Progress:\n")

            for line in lines:
                print(line.strip())

                parts = line.split("|")
                h = float(parts[2])
                total = total + h

            print("\nTotal Hours Studied:", total)

        except:
            print("No progress found yet.")

    elif choice == "3":
        print("Goodbye!")
        break

    else:
        print("Invalid choice")